name: msds692_final_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pandas=2.3.3
  - numpy=2.3.3
  - requests=2.32.5
  - aiohttp
  - tqdm
  - uvicorn=0.37.0
  - statsmodels=0.14.5
  - matplotlib=3.10.6
  - pip
  - pip:
      # FastAPI
      - fastapi==0.118.2
      - fastapi-cli==0.0.8
      - fastapi-cloud-cli==0.3.0

      # Google Cloud
      - google-cloud-storage
      - google-auth
      - google-api-core
      - google-genai==1.32.0

      # NBA API
      - nba-api==1.10.2
      - aiohappyeyeballs==2.6.1

      # Web scraping & HTML parsing
      - beautifulsoup4
      - lxml
      - html5lib
      - fake-useragent
      - requests-html

      # Streamlit & plotting
      - streamlit==1.50.0
      - plotnine==0.15.0
      - mizani==0.14.2
      - altair==5.0.1

      # Other utilities
      - python-dotenv
      - pydantic
      - greenlet==3.2.4
      - pyarrow==21.0.0
      - pyppeteer==0.0.25
      - pillow
      - pyquery
      - typing-extensions
